# Generated by Django 2.2.12 on 2021-07-08 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('bg_image', models.ImageField(default='', null=True, upload_to='media/events/')),
                ('yt_link', models.URLField(default='', max_length=300, null=True)),
                ('content', models.TextField()),
            ],
        ),
    ]
