# Generated by Django 3.2.4 on 2021-12-28 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank='True', default='default.jpg', null=True, upload_to='events/'),
        ),
    ]
