# Generated by Django 2.2.12 on 2021-07-17 17:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('author', models.CharField(max_length=40)),
                ('date_posted', models.DateField(default=django.utils.timezone.now)),
                ('content', models.TextField(max_length=400)),
                ('blog_link', models.URLField()),
                ('bg_image', models.ImageField(default='blog/dafault-blog.png', upload_to='')),
            ],
        ),
    ]
