# Generated by Django 3.2.4 on 2021-12-28 05:31

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('author', models.CharField(max_length=40)),
                ('date_posted', models.DateField(default=django.utils.timezone.now)),
                ('content', models.TextField(max_length=1000)),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('blog_link', models.URLField(blank=True, null=True)),
                ('thumbnail', models.ImageField(blank='True', default='default.jpg', null=True, upload_to='blogs/')),
            ],
        ),
    ]
