# Generated by Django 2.2.12 on 2021-07-18 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='bg_image_id',
            field=models.CharField(max_length=50),
        ),
    ]
