# Generated by Django 3.2.5 on 2021-07-23 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blog_bg_image_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='bg_image_link',
        ),
        migrations.AlterField(
            model_name='blog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
