# Generated by Django 3.2.4 on 2021-07-18 09:14

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='img/%y')),
                ('desc', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('url', models.URLField(blank=True)),
                ('urlTitle', models.CharField(max_length=20)),
            ],
        ),
    ]
