# Generated by Django 3.2.4 on 2021-12-27 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_alter_team_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='team',
            name='pic_id',
        ),
        migrations.AlterField(
            model_name='team',
            name='pic',
            field=models.ImageField(blank='True', default='', null=True, upload_to='team'),
        ),
    ]
