# Generated by Django 3.2.8 on 2021-10-17 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_remove_team_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_alumnus',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='team',
            name='year',
            field=models.PositiveSmallIntegerField(default=2021),
        ),
    ]
