# Generated by Django 3.2.4 on 2021-10-24 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_auto_20210723_1730'),
        ('team', '0003_auto_20210724_1808'),
    ]

    operations = [
    ]
