# Generated by Django 3.2.8 on 2021-10-17 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_auto_20211017_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='pic',
            field=models.URLField(max_length=1000),
        ),
    ]
