# Generated by Django 3.2.8 on 2021-10-24 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_alter_team_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='pic_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
