# Generated by Django 3.2.8 on 2021-10-25 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_team_pic_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='rank',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True),
        ),
    ]
