# Generated by Django 3.2.4 on 2021-10-26 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_merge_0003_auto_20210723_1730_0003_auto_20210724_1808'),
        ('team', '0006_position_rank'),
    ]

    operations = [
    ]
