# Generated by Django 3.2.4 on 2021-11-09 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_auto_20210708_1547 2'),
        ('team', '0003_auto_20210724_1808 2'),
        ('team', '0007_merge_20211026_1622'),
    ]

    operations = [
    ]
