version: '3.3'

services:
  web:
    build:
        context: .
        dockerfile: Dockerfile.prod
    ports:
      - 8004:8000
    command: sh -c "/code/entrypoint.prod"
    restart: always
    volumes:
        - "./sail/static:/code/web/sail/static"
        - "./sail/media:/code/sail/media"
        - "./db:/code/db"
        - "./assets:/code/assets"
    env_file:
        - ./.env.prod

