# Generated by Django 3.2.4 on 2021-10-21 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunity',
            name='slug',
        ),
    ]
