# Generated by Django 3.2.4 on 2021-12-25 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opportunity',
            old_name='skills',
            new_name='tags',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='slug',
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opportunity.role'),
        ),
    ]
