# Generated by Django 3.2.4 on 2021-10-21 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0002_remove_opportunity_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opportunity.role'),
        ),
    ]
