# Generated by Django 3.2.4 on 2021-10-21 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0003_alter_opportunity_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opportunity',
            old_name='skills',
            new_name='tags',
        ),
    ]
